# Generated by Django 4.2.2 on 2023-09-05 11:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.CharField(blank=True, max_length=500, null=True)),
                ('phone', models.IntegerField(blank=True, max_length=10, null=True)),
                ('student_id', models.UUIDField(blank=True, default=uuid.uuid4, null=True)),
            ],
        ),
    ]
