# Generated by Django 4.2.2 on 2023-09-05 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0004_alter_student_options_student_created_branch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='student',
        ),
        migrations.AddField(
            model_name='student',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rest_api.branch'),
        ),
    ]
