# Generated by Django 4.2.2 on 2023-08-24 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_img',
            field=models.ImageField(blank=True, default='spline.jpg', null=True, upload_to='profiles/'),
        ),
    ]
